### ISSUE TITLE
Authenticate with 3rd party provider on a mobile app and use the obtained token as a grant

### ISSUE THREAD

**Issue by simoneb** [jaredhanson/oauth2orize#106]
I have a question which doesn't directly pertain oauth2orize but it's somewhat related as I'll explain shortly.

I have a mobile app which calls HTTP APIs on my own server application which protects them using OAuth2 access tokens supplied by oauth2orize. I'm currently using the password flow to obtain access tokens and I would like to allow users to access my APIs without registering on my server but authenticating using their Facebook/Google/... accounts.

I'm thinking that if the architecture didn't involve a mobile app this would be simple and easily achieved using passportjs with a local strategy based on user credentials plus the built-in support for third-party oauth2 providers, although my server would still need to take care of creating/linking accounts.

With the mobile app involvement instead the flow doesn't seem so straightforward and I'm looking for inputs. My thoughts are that this can be achieved in a couple of ways, but in any case with no direct support from existing libraries.

The first option is that the mobile app authenticates with the 3rd party provider and obtain an access token (using a flow suitable for installed applications), then exchange this access token with an access token generated by my server (and my oauth2orize instance). So basically this would be like an additional grant type that oauth2orize would support, exchanging an access token coming from a 3rd party service with its own access token, that my own protected APIs would be able to accept. I'm not sure I can see all the implications of this flow but it feels the most straightforward, I'm just surprised that there doesn't seem to be any literature on the topic.

The second option I considered is to involve the server in the OAuth2 flow with the 3rd party provider. So the app would still trigger authentication with the 3rd party provider but instead of completing the OAuth2 flow entirely on the app it would complete on my server, simply using the classic authorization code flow with a redirect uri pointing at my server. The server would then be able to obtain an access token from the 3rd party service, handle account creation/linking and then generate an access token for the app (not sure how it would be sent back to the app though).

I would greatly appreciate any input!

**Comment by jaredhanson** [comment]
Either of the options you mention are workable in a mobile app scenario.  I personally like the first option you mention.  As you note, I'm surprised there isn't more literature on the topic as well.  I've been meaning to write up my findings at some point, but time...  The second option is used quite a bit as well.  Ultimately, its just a judgement call on how you want to implement things, the end result is the same.

Hope this helps!

**Comment by jamescoletti** [comment]
@jaredhanson, any progress on write-ups of your findings? We're also looking to add third-party signup/signin capabilities to our oauth2orize-based server and are evaluating different architectures. Seems it would be beneficial to create some custom exchanges to ease this type of integration as I imagine it's a common use case for a lot of folks. Any input would be appreciated.

**Comment by mitchellporter** [comment]
@simoneb Would love to hear what you ended up implementing to accomplish this.

**Comment by jamescoletti** [comment]
FWIW, we ended up implementing this pretty much exactly as @simoneb's first option outlines, with the only change being: the client exchanges the **authorization code** obtained by the third-party provider for a local access token, rather than the third-party access token for a local access token. (Our client apps never need the third-party access tokens.)

The flow is basically:

1. Client (responsible for implementing whatever redirects/SDKs/etc. needed for communicating with the third-party OAuth provider) authenticates the user against the third-party OAuth server and obtains an authorization code.
1. Client exchanges this authorization code with our local OAuth server for a local access token using the usual token endpoint, but with a custom `grant_type` we added, which oauth2orize makes very easy.

The custom grant request is something like:
```
{
  "grant_type": "google",
  "code": "7nmbR57H2PMYqsN7e29Qm424466395MGkN3cQE4u"
}
```

The custom token exchange handler we added to oauth2orize basically exchanges the authorization code for a third-party access token via server-to-server so it can obtain information from the user's Google+ profile, etc. before it ultimately returns our own local bearer access token.

This implementation fits into our flow quite cleanly and logically. Feedback welcome.

**Comment by anandsinghkunwar** [comment]
@jamescoletti I am trying to do something similar as you described. Can you share, how you created this custom "grant_type". Also I have a follow up, did you not use passport-google for obtaining profile information using access_token and wrote a custom thing for this? I was thinking of integrating this flow with passport-google, passport-facebook etc. to use for fetching user information etc. Any thoughts?

**Comment by jamescoletti** [comment]
@anandsinghkunwar The oauth2orize library lets you implement custom exchanges to handle custom grant types. Look at the default password grant implementation, which you can use as a template to write something that suits your specific needs:

https://github.com/jaredhanson/oauth2orize/blob/master/lib/exchange/password.js

The key is that the name of the function returned is used as the `grant_type` value. For example, sending `"grant_type": "password"` to the token endpoint works because the password exchange linked above returns a function with that name:

```javascript
return function password(req, res, next) { /* ... */ }
```

So if you want a custom grant type, implement your own exchange with a named function to match your custom grant type name. In your exchange, you can also do parameter validation if your grant needs custom parameters. In my previous comment, I mentioned ours expects a `code` parameter, which is the authorization code from Google's OAuth servers. Your exchange can make these custom parameters available to the grant handler callback.

Then in your oauth2orize setup, wire up the exchange and implement the grant handler callback. Something like:

```javascript
const oauth2orize = require('oauth2orize');
const oauthServer = oauth2orize.createServer();

// load my custom Google exchange:
const googleExchange = require('./src/lib/exchanges/googleExchange');

// add exchange to handle custom grant type
oauthServer.exchange(googleExchange((client, code, scope, body, done) => {
   // implement grant handler here, calling `done` with an error or your newly created local access token
   // the googleExchange makes the "code" param available to the callback
));
```
In response to your second question, we didn't use traditional passport social plugins like https://github.com/jaredhanson/passport-google-oauth2. These are great for most common use cases. In our case, we have our own OAuth server deployed, supporting lots of different types of client apps, supporting various user roles and additional user verification steps. For us it made sense to implement our own finer-grained API connectivity to the external services to fetch access tokens, profile info and perform other actions.

Hope this helps.
