### ISSUE TITLE
Renaming the OAuth parameters

### ISSUE THREAD

**Issue by chrisspiegl** [jaredhanson/oauth2orize#55]
Is it somehow possible to rename the parameters like: 
- client_id
- response_type
- redirect_uri

So that for example the `client_id` is `key` instead.

**Comment by docksteaderluke** [comment]
I recognize that this is an old issue, but my API uses camelCase everywhere for URL query parameters.

The `transaction_id` field can be renamed in `middleware/transactionLoader.js` using the `options` argument. Can we do the same for these parameters?

**Comment by jaredhanson** [comment]
No. There's nothing I dislike more than implementations that don't conform to spec

Transaction ID is renameable because it is an internal part of the dialogs with a browser, and does not effect compatibility

Please put compatibility with the 10000s of man hours put into existing OAuth libraries over consistency.  Other developers will thank you

**Comment by docksteaderluke** [comment]
Fair enough.

I guess I don't understand why an RFC doc would specify the use of a particular naming convention that isn't defined so particularly anywhere else. Seems to me that would lead to inconsistencies (what if another RFC doc specified the use of camelCase?). As far as I know, there are no specifications for URL query parameters that require the use of the snake_case naming convention (unless there are and I can't find them).

Regardless, none of the issues above are your problems. If the spec says it, that's good enough for me.
